### ISSUE TITLE
Alertes de sécurités des modules installés dans nos applications en prod

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#104]
Mentionner des services comme https://snyk.io/ ?

**Comment by oncletom** [comment]
Oui, puis https://nodesecurity.io/ et http://npmjs.com/nsp :-)

**Comment by oncletom** [comment]
Fait dans c48d2ac et f251ffa.

**Comment by DirtyF** [comment]
Note: Pour les alertes maintenant on peut aussi utiliser `npm audit` (https://docs.npmjs.com/getting-started/running-a-security-audit)

**Comment by oncletom** [comment]
Tout à fait @DirtyF 

Documenté ici dans le chapitre consacré à npm : https://oncletom.io/node.js/chapter-05/#audit
