### ISSUE TITLE
Mentionner npm init -y ?

### ISSUE THREAD

**Issue by ThomasG77** [oncletom/nodebook#105]
J'ai tendance à préférer `npm init -y` à `npm init`
Je considère cette préférence comme une astuce quand on ne veut pas passer en mode interactif mais générer le fichier directement

**Comment by oncletom** [comment]
C'est une bonne idée de mentionner le raccourci oui :-)

**Comment by DirtyF** [comment]
👍 

D'une manière générale, on apprend toujours des trucs en consultant l'aide des commandes  😃 

```sh
npm init --help
npm init [--force|-f|--yes|-y]
```
