### ISSUE TITLE
Versionner ses modules avec SemVer

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#107]
Lors du passage sur SemVer, il serait intéressant de mentionner l'existence de [npm version](https://docs.npmjs.com/cli/version) : 

```sh
npm version --help
npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]
```

L'avantage de cet outil, est qu'il va incrémenter la version dans le fichier `package.json` mais également tagger la version dans Git. Rudement pratique 😄

**Comment by oncletom** [comment]
Toutaf', très bonne suggestion :-)

**Comment by lellex** [comment]
La notion de SemVer est abordée 2 fois
- https://oncletom.io/node.js/chapter-01/index.html#semver
- https://oncletom.io/node.js/chapter-03/index.html#_configuration

Est-ce que ce n'est pas un peu répétitif ?

**Comment by oncletom** [comment]
Oui ça fait doublon.

Il faudrait que le chapitre 3 ne contienne que des aides au choix de version, et faire mention au fonctionnement de semver dans le chapitre 1.

**Comment by oncletom** [comment]
(à vous lire j'ai presque l'impression que vous faites une lecture côte à côte 😄)
