### ISSUE TITLE
Phrase incomplète à propos des middlewares d'Express

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#109]
https://github.com/oncletom/nodebook/blob/master/chapter-03/index.adoc#express

Son système de _middlewares_…

**Comment by oncletom** [comment]
Ah, bien vu merci ! 🙂 

Je vais réécrire cette partie donc c'est pas très grave :-)
Je me suis rendu compte que ça faisait un peu doublon avec la fin du chapitre 2 et qu'il manque de quoi faire une webapp classique, avec un peu d'API REST.
