### ISSUE TITLE
Automatiser avec npm run 

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#112]
Dans la partie automatisation, tu mentionnes `grunt`, `gulp` et le package `npm-run all` mais pas `npm run`.

**Comment by oncletom** [comment]
Hm, pourtant j'en parle ici https://oncletom.io/node.js/chapter-03/#npm-scripts

Manque d'ordonnancement logique peut-être ?

**Comment by DirtyF** [comment]
S'il y a une section pour l'utilisation de `npm run` ailleurs, un simple rappel ou un renvoi — on ne lit pas forcément un livre in extenso, dans l'ordre — serait le bienvenu.

> Vous pouvez aussi choisir de vous reposer entièrement sur les scripts npm pour automatiser les tâches récurrentes comme nous l'avons vu plus haut (référence) Dans ce cas le package `npm-run-all` se révèle particulièrement intéressant pour vous aider à paralléliser l'exécution de vos scripts, etc.

**Comment by oncletom** [comment]
Ouaip, entièrement d'accord 🙂

**Comment by DirtyF** [comment]
Sur la partie front-end je découvre qu'il existe des outils comme https://github.com/esr360/Noah/ qui peuvent faciliter le passage aux scripts npm.

**Comment by oncletom** [comment]
Aaaaaaaah du boilerplate !

Par la force des choses c'est apparu ici https://github.com/oncletom/nodebook/blob/b44f6a4445acc7a97f5d393066afded5b276b41f/chapter-04/package.json#L8

Qu'est-ce qui te manque, toi, pour te sentir à l'aise avec les scripts npm ? En écrire toi-même sans un outil qui te génère le code des scripts npm ?

**Comment by DirtyF** [comment]
Je trouve que c'est intéressant d'aller regarder les scripts node de ces boilerplates, ils peuvent être une source d'inspiration pour créer ses propres scripts et se passer de Gulp ou Grunt.

**Comment by oncletom** [comment]
Cf. #184, y'aura un chapitre dédié à npm.

**Comment by oncletom** [comment]
En train d'être couvert via a837121dd035500e31ece7f1cb9e3142b15d8c90, 163d98cce4642990d94fa03154067e8072507b04 et 51b5f5cca54e454a103c8b746441b45e26b4143a
