### ISSUE TITLE
nodebook cli

### ISSUE THREAD

**Issue by oncletom** [oncletom/nodebook#119]
Plusieurs objectifs :

- [x] lire une copie à jour de l'ouvrage
- [x] installer les dépendances de chaque chapitre
- [ ] parcourir les exemples d'un chapitre et jouer avec

```bash
npm i -g nodebook@latest

# Démarre le serveur de lecture + ouvre le navigateur
nodebook read

# Installe un chapitre 3
nodebook chapter install 3

# Ouvre les exemples du chapitre 3
nodebook chapter open 3
```

**Comment by oncletom** [comment]
Il est encore nécessaire d'avoir l'extension navigateur pour lire l'ouvrage.


Iil manque une commande où le terminal est emmené vers le répertoire du chapitre, probablement `nodebook chapter 4`.

`nodebook chapter 4 open` ouvrirait ce répertoire dans le finder/explorateur de fichiers.

`nodebook chapter 4 start` démarrerait le serveur http dédié uniquement en présence d'un fichier `server.js` à sa racine (ou de présence d'un `npm start` dans le package.json).

**Comment by hsablonniere** [comment]
@oncletom Si tu passes à Lyon, profites en pour rencontrer @Mogztter et parler de nodebook et asciidoctor.js 😉

**Comment by oncletom** [comment]
@hsablonniere aaaah mais j'y suis en ce moment !
