### ISSUE TITLE
Tooling : la copie vidéo ne fonctionne pas sur Travis

### ISSUE THREAD

**Issue by oncletom** [oncletom/nodebook#132]
```bash
mkdir: cannot create directory ‘dist/chapter-04/videos/’: Permission denied
make: *** [dist/chapter-04/videos/browser-sync.mp4] Error 1
```

Aucune idée du pourquoi, en correspondance dans une gare donc je regarderai plus tard.

**Bloque les déploiements**

**Comment by oncletom** [comment]
Problème de permissions quand le répertoire est créé par Asciidoctor avec Docker + linux.

Solution : `mkdir -p` juste avant de générer le HTML depuis le ADOC.

Maintenant trouver comment obtenir les fichiers git-lfs sur Travis.

**Comment by DirtyF** [comment]
à priori ce n'est pas encore nativement supporté par les images si j'en crois https://github.com/travis-ci/travis-ci/issues/3634#issuecomment-220554067 qui donne une solution de contournement.

**Comment by oncletom** [comment]
@DirtyF En lisant https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/ je croyais que c'était dispo sous Trusty. Ptête pas en container mode va savoir.

Toujours est-il, c'est résolu dans 8996212 :-) (je suis tombé sur le même commentaire d'_issue_ d'ailleurs ; bonne pioche on dirait !)
