### ISSUE TITLE
CH4: Cohérence du sommaire avec la table des matières

### ISSUE THREAD

**Issue by fvsch** [oncletom/nodebook#137]
(Attention: “Table of contents”, à traduire.)

Le sommaire est perturbant car il n'a pas l'air de correspondre exactement à la table des matières. Par exemple:

- "Gérer les dépendances externes" en premier, mais "Exécuter Node dans les navigateurs web ?" et "Écrire dès à présent le code du futur" en items 1 et 2 de la TOC.
- "Des requêtes AJAX au temps-réel" dans la TOC -> rien dans le sommaire.

Faut-il un sommaire sous forme de liste (au lieu de phrases)? Un titre différent de "Sommaire" si c'est un aperçu du contenu incomplet?

**Comment by fvsch** [comment]
Sur la première partie, "Éxécuter Node dans les navigateurs web ?", la réponse permet aussi de présenter le contenu du reste du chapitre. Peut-être alors un titre plus large, par exemple "Quel rapport entre Node et les navigateurs web ?"

**Comment by oncletom** [comment]
Oui tu as raison @fvsch – la ToC est générée automatiquement (et n'apparaitra pas sur la version papier) tandis que le sommaire est écrit à la main … je me demande si je ne vais pas générer le Sommaire à partir des titres de niveau 1.

C'est une bonne question pour la liste/phrase – il me semblait que c'était une liste dans les autres ouvrages de la collection mais ça me met le doute… je vérifierai.

**Comment by oncletom** [comment]
Le sommaire automatique c'est pas top – peut-être un indicateur sur un besoin à remanier les titres.

J'ai mis en sommaire :

- Polyfills et compatibilité _ECMASCript_
- Importer des modules _npm_ pour le web
- Créer du code modulaire, avec ou sans _framework_
- Échanges de données en temps-réel
- Outillage utile au quotidien
- Tester son code et la compatibilité avec les navigateurs web
