### ISSUE TITLE
CH 4.2 - divers retours

### ISSUE THREAD

**Issue by fvsch** [oncletom/nodebook#138]
Librairies ou bibliothèques?

- Bibliothèque(s): un usage
- Librairie(s): 24 usages dans le chapitre

## Intro

Les détails sur esprima sont intéressants mais ça nous plonge dans la notion d'AST assez précise, et des "détails" historiques, c'est un peu rebutant de prime abord. Il y a beaucoup de name dropping d'outils "révolus" aussi.

Peut-être commencer par "on peut faire X (et voici un aparté historique sur comment)" plutôt que par l'aparté historique qui débouche sur "bon, du coup c'est cool on peut faire X"?

La phrase qui devrait arrivée avant les détails à mon sens:

>  Toutefois si on ne devait retenir qu’une chose de tout ceci c’est qu’il est désormais normal d'écrire du code moderne en anticipation des futurs standards et de le faire fonctionner sur les navigateurs actuels et anciens.

## 4.2.1

> une compatibilité aussi antique que désirée

Qu'est-ce que ça veut dire?

## 4.2.2

> à des vitesses différentes par les différents concepteurs de navigateurs web

"par les navigateurs web" simplifie la phrase.

> rythmes de mises à jour en cycle court – on parle de six à neuf semaines pour la plupart.

6-9 pour Firefox et Chrome, mais annuel pour Safari et Edge (hors Technical Preview).
Donc un tiers significatif est sur du 1 an.

Sur Babel (que je connais à peine): un exemple de config donne une liste de 2 presets:

```
{
  "presets": [
    "es2015",
    "es2016"
  ]
}
```
mais on ne parle pas de la possibilité de cummuler les presets. Pour le néophyte (moi), ça se lit comme "je veux compiler en ES 2015 ou en ES 2016 ou euh les deux euh je sais pas".

Aussi pourquoi donner le nom et l'URL de doc d'un preset, mais sans un mot sur ce qu'il fait? À la rigueur je préfère avoir son nom et une description de son utilité, et dans le bloc de renvoi vers la doc un renvoi vers une page de doc sur les presets.

Sur l'exemple de code `babel-es2015ified.js` les deux numéros de notes sont repris, mais il n'y a pas de notes en dessous de l'exemple. Peut-être supprimer les numéros?

Autre question: est-ce qu'il y a des inconvénients à l'usage de la transpilation ES 201x vers ES5? Je pense à des problèmes de perf d'exécution, de poids rajouté au build…
À mentionner dans le chapitre, ou c'est de trop?

## 4.2.3

Le deuxième paragraphe («La déstructuration, les constantes et les classes sont…») arrive comme un cheveu sur la soupe. Mon confrère qui relit avec moi a fait "wat?" :)

> Un polyfill nous garantit la présence d’une fonctionnalité, peu importe l’ancienneté du code et du navigateur l’exécutant.

Garantit, c'est un mot un peu fort. Surtout que certains polyfills sont compatibles uniquement avec des versions relativement récentes (par exemple IE11).

> l’objet global Promise n’existe pas dans Internet Explorer 9, entre autres.

IE11 est un meilleur exemple (plus de parts de marché, et ne donne pas l'impression qu'à partir d'IE10 c'est bon).

> L’inclusion d’un polyfill `Promise`

Point langue, peut-être ajouter un article et parler de «polyfill de `Promise`»?

> polyfill.io possède une documentation très complète et illustrative de son fonctionnement.

"polyfill.io fournit une documentation complète et fournie en exemples"?

Code `polyfill.io.html`: pourquoi le script dans le `<head>` et pas juste avant le script suivant?

> L’inconvénient est que nous chargeons du code qui sera inutile les navigateurs et environnements …

Manque un mot.

> Enfin, une dernière méthode est l'appel explicite de polyfill. Nous faisons une référence explicite au polyfill mais à l’inverse, nous ne modifions pas les objets globaux :

J’ai eu du mal à comprendre ce dont on parlait et l'exemple donné. (Mon collègue non, par contre.)

Peut-être tourné ainsi?

> Enfin, nous pouvons appeler directement un polyfill. Plutôt que de charger un script qui modifiera ou créera un object global (par exemple `window.Promise`), nous appelons explicitement notre polyfill : [exemple]

Il manque aussi la notion de comment ce module va être chargé au final, mais c'est traité plus tard avec la question du chargement natif et du bundling j'imagine. À voir si on peut y faire référence ici, après l'exemple de code?

**Comment by oncletom** [comment]
Merci beaucoup @fvsch pour ces remarques qui font réfléchir :smiley:

Elles emmènent vers plus de clarté et moins d'ambiguïté sur des points assez sensibles, j'aime beaucoup !
