### ISSUE TITLE
ch4 - optimiser ses ressources graphiques

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#140]
SVG est rapidement évoqué à juste titre car incontournable de nos jours.

Du coup je trouve dommage de ne pas citer le module npm svgo: https://github.com/svg/svgo

**Comment by oncletom** [comment]
@DirtyF j'ai assez peu parlé des outils car j'en ai déplacé pas mal dans l'annexe A. Dont SVGO.

Il se trouve aussi qu'imagemin optimise aussi les SVG… avec SVGO.

Au final on se fout de namedropper des noms d'outils. Faut savoir qu'on peut optimiser des ressources graphiques, peu importe leur nature.

**Comment by DirtyF** [comment]
Au temps pour moi, je ne savais pas que c'était `svgo` qui était utilisé par imageOptim qui est mentionné en effet pour l'optimisation des ressources graphiques. 

L'idée ici n'est pas de faire du simple namedropping mais de monter que l'écosystème `npm` propose aujourd'hui l'outillage de référence pour le front-end et que donc les développeurs front-end et les webdesigners devraient s'y pencher ne serait-ce que pour bénéficier de ces outils éprouvés et efficaces.

**Comment by oncletom** [comment]
@DirtyF oui t'as grave raison – y'a tellement de matière pour aller plus loin sur ce sujet… je ne suis pas sûr que le contenu existant suffisant pour donner envie/faire passer le message de la richesse de l'écosystème npm.

Les générateurs de sites statiques auraient tellement leur place ici aussi, d'ailleurs…

**Comment by DirtyF** [comment]
Clair qu'il y aurait de quoi faire un bouquin dédié sur l'utilisation de `npm` pour le développement front-end, ) la lecture des premiers chapitres ton ouvrage n'a pas l'air d'avoir vocation à cela. Tu as surement raison de viser un public plus ciblé, à savoir en priorité les développeurs JS de demain, en leur fournissant un bon aperçu de l'écosystème, des contextes d'utilisations, exemples à l'appui. On voit bien qu'il y a déjà beaucoup à dire, tu ne peux pas te permettre d'être exhaustif sur cette utilisation annexe de node. Du coup l'annexe, ça me parait le plus judicieux pour ce genre de choses. Aux gens d'aller creuser en fonction de leurs besoins et de leur profil.
