### ISSUE TITLE
Chapitre 2 : Relecture de 4. Node, JavaScript et ECMAScript

### ISSUE THREAD

**Issue by JulienPradet** [oncletom/nodebook#146]
Salut,

Voilà une première liste de remarques sur la 4ème partie du Chapitre 2. Je pensais avoir lu tout le chapitre 2, mais il y a des bouts qui ont changé de place, et tout ce qui est à partir des Desgin Patterns qui est nouveau ! Héhé, ca va m'occuper pendant un moment. :raised_hands: 

En espérant que ce soit utile. Tout n'est pas forcément pertinent en fonction de ce que tu veux faire, mais je me suis dit que ça coutait rien de le remonter :)

## 4.3.4. Array

> La méthode filter quant à elle retourne un nouveau tableau ne contenant que les éléments retournant une valeur positive

Etant donné que l'exemple se fait sur une comparaison `< 10`, c'est assez perturbant, je trouve. Est-ce que ce serait mieux avec 'un booléen positif', voire 'le booléen `true`' ? J'en profite pour dire que ce serait peut-être bien de faire une partie sur les Booléens en tant que primitive ? C'est notamment utile quand on chaîne les opérations booléennes et qu'on veut être sûr que la valeur finale est un booléen :
```
const objectKeyIsNotEmpty = Boolean(object && object.key)
```

### Rest vs Spread

Je ne suis pas tout à fait sûr de moi, mais il me semble que dans le cas de 'décomposition', c'est l'opérateur [`rest`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters). C'est ce que je comprends sur [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) en tout cas. L'opérateur [`spread`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) permet de fusionner des objets/tableaux sur les right values.

D'ailleurs, je n'ai pas l'impression que tu en parles du `spread` dans les primitives. Tu es resté sur `Array.prototype.concat` et `Object.assign`. C'est volontaire ?

Le risque en parlant du spread, c'est que pour les objets, ce n'est pas encore officiellement dans la spec ECMAScript (c'est en stage 3), même si c'est disponible dans node 7. Ca peut rajouter un niveau de confusion en plus. Mais l'avantage c'est que c'est plus agréable à écrire :)

### Nommage des variables lors de la décomposition

Le but du livre n'est pas d'expliquer en détail tous les éléments de la spec, mais est-ce que ce serait quand même intéressant de parler de la possibilité de renommer les variables quand on fait du destructuring ?

```
const {key: variableName1} = object
const {key: variableName2} = object
console.log(variableName1, variableName2)
```

Personnellement, ça m'est entre autre utile quand j'implémente des fonctions de comparaison pour `Array.protoype.sort`.

## 4.3.7. Function

Je trouve que ça arrive assez tard. Notamment parce que dans les exemples sur les tableaux et les objets, tu utilises déjà beaucoup de `arrow functions` qui sont assez perturbantes.

Et ce serait l'occasion aussi d'introduire le fait qu'une fonction peut être mise dans une variable (sans aller jusqu'à dire que les fonctions sont des objets du premier ordre `first class functions`) et que c'est pour cette raison qu'on peut facilement faire des callbacks, etc. Je ne suis pas sûr que ce soit une bonne idée, parce que c'est un concept qui n'est pas forcément simple à prendre en main quand on vient d'un autre monde. Mais je propose quand même ! :)

Par ailleurs, je trouve que le `this` est utilisé mais jamais vraiment expliqué. Le risque est que ceux qui viennent d'autres langages se fassent piéger en pensant que les méthodes de classe fonctionne de la même facon que dans un langage objet traditionnel, ou bien qu'une arrow function peut être bindée. Le problème c'est que ça mérite sûrement de longs paragraphes d'explication et que ce que tu as fait ressemble peut-être plus à un glossaire de primitives. A défaut, peut-être qu'il y aurait des ressources sur lesquels les lecteurs pourraient être redirigés.

### Polyfill 

Ca pourrait être bien de mettre une définition glossaire de 'polyfill'. J'ai l'impression que c'est quelque chose de très spécifique au monde du js qui pourrait perturber un lecteur qui n'est pas habitué.

### Cas de figure dans un then

> le callback de succès ne retourne rien : le prochain then transmet à nouveau le résultat de la promesse ;

Le prochain then transmet undefined si le succès ne retourne rien.

```
Promise.resolve(1)
  .then((a) => console.log(a)) // 1
  .then((a) => console.log(a)) // undefined
```

Mais je ne suis pas sûr de comprendre la phrase.

## 4.3.14. JSON

> Retourne `'{\n "ECMAScript": 5.1\n}'`

Il y a bien deux espaces dans la source, mais asciidoc/chrome semble le manger à l'affichage.

### currency-format.js

Dans l'exemple `currency-format.js`, est-ce que le bind n'est pas un peu compliqué ici ? Je suis plus adepte des arrow functions pour ça parce que je trouve ca plus lisible. Mais c'est purement une remarque de style qui peut facilement être ignorée.

```
const formatNumber = (separator, precision) => (number) => {
  return number.toFixed(precision).replace('.', separator);
};

const setupFormatter = currencyId => {
  const currency = currencies[currencyId];
  const f = formatNumber(currency.decimal, 2);

  return function formatCurrency(amount) {
    return f(amount) + currency.symbol;
  };
};
```

### Fonctionnement des modules

Je crois, dans la première version que j'ai lu, avoir vu une explication du l'exécution du fonctionnement de CommonJS. C'était super intéressant et c'est le genre d'informations que je viens chercher dans un livre.

Cela dit, en tant qu'introduction pour apprendre à utiliser node.js c'est vrai que ce n'est pas très utile. 

## 4.4.4. require

Dans l'exemple, je trouve que ce n'est pas évident de base que le fichier `require.js` est dans le dossier `examples`. Je le sais parce que j'ai regardé les sources, mais quand je pense à un lecteur papier, je me dis qu'il ne le saura pas forcément.

Par ailleurs, c'est intéressant de savoir que quand on cherche un dossier, le main du package.json sera retenu. Par contre, ce serait bien d'ajouter que si le package.json n'est pas présent, c'est le fichier index.js qui est récupéré.

**Comment by oncletom** [comment]
Merci pour tous ces précieux retours @JulienPradet 👍 🙂 

J'ai en effet réorganisé des contenu en repensant le chapitre 3 qui devenait une liste de courses sans fin, cf. #134.

Je rebondis sur tes retours un peu plus tard dans la journée  :-) Y'a aussi ceux de Florens dans #138 que j'aimerais (re)voir par la même occasion.

Un excellent dimanche à toi et à demain dans tous les cas :-)
