### ISSUE TITLE
https://scalingo.com/ en PaaS

### ISSUE THREAD

**Issue by oncletom** [oncletom/nodebook#152]

**Comment by yannski** [comment]
si vous avez besoin de renseignements sur Scalingo, faites moi signe :)

**Comment by oncletom** [comment]
Merci @yannski !

T'as peut-être des pointeurs à me donner avant que je me mette à regarder ?

**Comment by yannski** [comment]
Yep, par ici : http://doc.scalingo.com/languages/javascript/nodejs/getting-started-with-nodejs/

**Comment by oncletom** [comment]
Merci :-)
