### ISSUE TITLE
À propos d'outils pratiques pour les auteurs : sedy

### ISSUE THREAD

**Issue by enguerran** [oncletom/nodebook#155]
Que penses-tu de mettre [sedy](https://github.com/marmelab/sedy) en place sur ton dépôt. Ça te permettrait de pouvoir proposer des modifications facilement aux PR qui te sont proposées.

**Comment by oncletom** [comment]
J'ai tenté de l'installer mais le repo n'apparait pas dans la (très courte) liste.

Bug déposé par ici marmelab/sedy#76

**Comment by enguerran** [comment]
C'est réparé ! Cf. https://github.com/marmelab/sedy/pull/81

**Comment by oncletom** [comment]
@enguerran oui très juste et je l'ai activé pour ce repo, normalement 🙂 

Merci pour la suggestion, fort pratique !
