### ISSUE TITLE
Ch 6 1.4 console.log (error, info) / debugger / console chrome remote

### ISSUE THREAD

**Issue by Inateno** [oncletom/nodebook#158]
La console permet souvent de débugger sans forcément rentrer dans les points d'arrêts etc, en mode dév (et même préprod) c'est très bien même si ça peut ralentir l'application (à prévenir en prod donc).

Je vois bon nombre de personnes ne l'utilisant pas assez alors que en suivant ce qu'il se passe dans la console on trouve vite le problème (sans parler du fait que l'on peut logger des objets/array/whatever, et que l'on peut coloriser / exporter les flux dans les fichiers logs distinct (en prod par exemple, on vire les logs console mais on garde l'output fichier qui est async, en réduisant le level de trace a info ou warn).

Vient le debugger, VSCode permet de se connecter en direct ou en remote avec une conf par défaut déjà bien (d'autres aussi je suppose, je ne les connais pas tous :) ).

Et pour finir https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.sm1dgz668 (un peu lourd à mettre en place mais worthy).

**Comment by SebastienElet** [comment]
Pour la prod, je pense garder tout l'output de mes process sur `stdout` et laisser la responsabilité de logger dans un fichier / syslog / db / whatever a mon process manager (`pm2` / `systemd`). Je trouve que c'est plus dans la philosophie unix et ça évite de devoir gérer des trucs chiant comme les signaux pour `logrotate` & co.

**Comment by oncletom** [comment]
Plutôt d'accord avec @SebastienElet – trouver le problème via les logs mais ne pas déboguer à distance (recréer les conditions). Déboguer via l'inspecteur sur une machine non-prod.

**Comment by Inateno** [comment]
Pour rentrer dans le détail.
Perso j'utilise winston et j'en instancie un par canal pour avoir des fichiers logs bien distinct en plus.
(http_access.log, server.log, special_api.log).
ça plus variable d'environnement qui delete les console.log et ne garde que les .warn et .error.

Au moins t'as toutes les façon d'accéder a ton log.
Et comme je disait le log en console ça ralentit l'application sur de fortes charges, donc perso en prod je dégage juste tout ce qui passe dans la console, ça va direct dans un fichier et c'est tout (le winston Console et le winston File permettent la distinction).

Mais je comprend parfaitement ton argument @SebastienElet  :) faut dire que je suis pas très philo unix de base vue que je fais principalement du dév windows (le côté obscur est parmi vous).

**Comment by oncletom** [comment]
Je comptais parler de Sentry.

Facile à mettre en place et ça fait super bien ce travail.
On peut commencer gratuit et passer payant.
Ou aller vers d'autres solutions plus complexes à mettre en place une fois qu'on a compris les mécanismes.
