### ISSUE TITLE
Ch 6. 6 Scaler (ou chapitre complet ?)

### ISSUE THREAD

**Issue by Inateno** [oncletom/nodebook#159]
Cela rejoint le cluster mais est plus global. Point que l'on a identifié comme "gros" durant le ToulouseJS du 06/03, parler du scaling (en général).

- cluster
- micro-services
- partage de session
- worker pool

Peut être lié à ce chapitre ou dans un autre, mais le caching est étroitement lié au partage de sessions.

**Comment by oncletom** [comment]
Cluster peut être intéressant car c'est de l'utilisation pure de Node – micro-services c'est de l'architecture d'applications.

Le partage de sessions c'est lié non ? Tu sous-entends que les sessions ne doivent pas être sur une seule et même machine c'est ça ?

Worker pool c'est cool – je me demande ce qu'il existe en équivalent de sidekiq avec Node – le pattern c'est de ne pas faire de traitement même asynchrone dans le même thread mais de le déplacer ailleurs que l'application principale.

**Comment by SebastienElet** [comment]
Il serait intéressant également de parler des différentes techniques pour servir du node : 
 - [upstart] + [monit]
 - [haproxy] + systemd
 - [pm2]
 - [forever]
 - Nginx + [phusion-passenger]
 - Docker / [rkt]

[upstart]: http://upstart.ubuntu.com/
[monit]: https://mmonit.com/monit/
[haproxy]: http://www.haproxy.org/
[pm2]: https://github.com/Unitech/pm2
[forever]: https://github.com/foreverjs/forever
[phusion-passenger]: https://www.phusionpassenger.com/
[rkt]: https://github.com/coreos/rkt

**Comment by Inateno** [comment]
Quand je parle des micro-service c'est en effet une architecture d'application, mais pour en faire et pour avoir cherché de la doc dessus, le pattern d'archi uniquement n'est pas suffisant pour l'appliquer (et au final pas si compliqué quand tu fais de la recherche et des tests).

C'est plus pour parler des "do and don't".

Et oui le partage de session est lié au micro-services, mais il est aussi lié au scale horizontal. Et dans les deux cas tu n'as pas les mêmes exigences.

Par exemple en micro-services il faut penser a faire des req.session.save( () => { res.send( "ok" ) } ) lors de traitement car si tu fais des suites d'appels aux différents serveurs, ta session n'est pas encore à jour et donc problème.

Alors que en scale-h (sans micro-services) tu n'as en général pas besoin de savoir ce détail.

Même si le connecteur express/redis est très/très/très simple à mettre en place, c'est toujours bien d'aborder la théorie le pourquoi et le comment (avec toujours les do and don't).
Notamment aussi parce qu'on fait beaucoup de choses en async.

Je ne m'y connais pas trop en worker-pool, pour moi c'est plus une implémentation haut-niveau des cluster (lancer X thread pour faire telle ou telle chose, en gros), j'imagine qu'il y a une tripotée de npm ;)

**Comment by SebastienElet** [comment]
Pour le scaling, il vaut mieux oublier les sessions et utiliser JWT, ça simplifie beaucoup les choses.

**Comment by Inateno** [comment]
En effet les JWT pour l'authent' c'est cool. Cela ne résoud pas tout et tout n'est pas stockable en DB, dans ce cas la session reste pertinente.

Je trouve que l'on met bien en lumière la difficulté du choix pour quelqu'un qui ne connaitrais pas tout ça (même si ce n'est pas strictement lié a NodeJS j'en convient).

**Comment by oncletom** [comment]
Hello ! 

Dans l'optique de terminer la première édition dans les prochaines semaines (Cf. nouvelle table des matières dans #184), ce sujet mérite sa place mais pas tout de suite tout de suite.

Merci pour vos conseils et suggestions 🙂

**Comment by oncletom** [comment]
Coucou,

Je trouve le sujet intéressant, il peut être abordé mais seulement en surface. Ça pourrait faire l'objet d'un ouvrage spécialisé à part entière. Si quelqu'un·e se sent, je peux vous mettre en contact avec Eyrolles si c'est quelque qui vous intéresse — ou me contacter pour creuser l'auto-édition.
