### ISSUE TITLE
Foreword > Preamble.adoc > Typo...

### ISSUE THREAD

**Issue by flyusfly** [oncletom/nodebook#160]
Oncletom,

Grâce à HumanCoders, je suis tombé sur ton article/aventure.
[http://news.humancoders.com/t/developpement/items/15018-ecrire-un-livre-en-2017](http://news.humancoders.com/t/developpement/items/15018-ecrire-un-livre-en-2017)

J'ai commencé la lecture de ton livre :
C'est propre, clair, fluide, vulgarisé, sans ambiguïté, détaillé, historiques et anecdotes, ...
Pour le moment, c'est un vrai plaisir à lire...

Voici ma modeste contribution pour le moment.

**Rubrique** : foreword.
**Fichier** : preamble.adoc
**Phrase** :

_"Ces principes traversent le temps et vous donnerons..."_
devient
_"Ces principes traversent le temps et vous donneront..."_

Un énorme merci pour ce travail phénoménal...
:-)

**Comment by oncletom** [comment]
Ah trop bien ! Il faut dire merci à @antoinentl de l'avoir écrit suite à ce [meetup à Grenoble](http://www.la-coop.net/evenement/ecrire-avec-github/) :-)

Merci pour ta contribution et le partage de ton ressenti 🙂 
J'espère que le reste du contenu te permettra de continuer à mêler apprentissage et plaisir.
