### ISSUE TITLE
Stylus absent du listing des modules

### ISSUE THREAD

**Issue by Scriptura** [oncletom/nodebook#177]
Bonjour. Parmi les preprossesseurs je pense que Sass devrait arriver en première position avant Less en raison de sa renommée (même si perso je ne l'utilise plus depuis longtemps).

Et surtout le grand absent de cette sous liste est Stylus, le pendant de Pug au niveau syntaxe :

https://www.npmjs.com/package/stylus

**Comment by oncletom** [comment]
@Scriptura salut 👋 tu fais référence à quel passage/quel chapitre ? 

Dans la partie consacrée au frontend, je ne me suis intéressé qu'à Sass ; cf. https://oncletom.io/node.js/chapter-04/index.html#node-sass

Stylus n'a pas reçu de mises à jour depuis 1 an, n'a probablement pas trop d'avenir devant lui et des approches comme PostCSS sont plus intéressantes car modulaires/à la demande. C'est ce qui m'inciterait à ne pas m'attarder dessus — on pourrait le lister bien sûr mais la liste de courses est déjà bien assez longue :-D

**Comment by Scriptura** [comment]
Je faisais référence à [Sélection de modules npm, 10. Préprocesseurs](https://oncletom.io/node.js/appendix-a/index.html#_pr_processeurs).

Je sais que l'on regarde un dépôt à son activité... mais :
- si l'on y regarde de plus près on s'aperçoit que Stylus est deux à trois fois moins téléchargé que Less, ce qui reste tout de même énorme (56 986 downloads in the last day), à comparer avec certains outils de template juste pour voir (exemple avec Swig : 5 576 downloads in the last day).
- si l'on y regarde de plus près encore on s'aperçoit que c'est l'un des 5 préprocesseurs par défaut proposé sur CodePen, utilisé qui plus est par certains grands gourous du css, tel qu'[Ana Tudor](https://codepen.io/thebabydino/pen/pyMyPx?q=stylus&limit=thebabydino) (quoi que bon : elle, elle est à l'aise avec tout...).

Enfin ne jamais oublier qu'il y a un énorme décalage entre les outils développés à ce jour et leurs reports sur npm (la dernière MAJ de Stylus [remonte à un mois](https://github.com/stylus/stylus/)). Des outils tels que Pug ont mis plus de 6 mois avant de faire certaines de leurs mises à jour sur npm (je le sais j'attendais la MAJ d'un bug de Pug avec impatience). Et que dire de [imagemagick](https://www.npmjs.com/package/imagemagick) "published 5 years ago" ! Bien sûr on peut trouver cette dernière ressource à jour en dehors de l'environnement npm, mais quel dommage tout de même...

**Comment by oncletom** [comment]
Ah oui je vois, merci :-)

J'ai dumpé toute une partie du chapitre frontend dans cette annexe. Ça paraitrait pertinent de voir stylus figurer à cette liste en effet 👍

**Comment by DirtyF** [comment]
> Stylus n'a pas reçu de mises à jour depuis 1 an, n'a probablement pas trop d'avenir devant lui et des approches comme PostCSS sont plus intéressantes car modulaires/à la demande. 

Et c'est un peu pareil pour Less et Sass (qui passe en Dart et qui ne sera peut-être plus aussi maintenu). Quoi qu'il en soit je fais le même constat que toi, on est sur des approches plus modulaires, voire carrément du CSS in JS. De plus il me semble qu'en plus les avancées de CSS font que les mixins et autres variables proposées à l'arrivée des préprocesseurs il y a 10 ans ne sont plus aujourd'hui une raison suffisante pour y avoir  systématiquement recours.  Je dis ça alors que j'adore pouvoir utiliser l'imbrication de l'indentation 😄 

En terme d'effort, je me dis que tu préfères peut-être parler du support natif de l'import de modules JS ou via WebAssembly dans les navigateurs ?

**Comment by Scriptura** [comment]
J'en ai fait beaucoup et je reconnais que ce n'était pas nécessaire. Je voulais surtout souligner les écarts (pour ne pas dire l'obsolescence) entre les dépôts npm et l'avancée réelle des développements de chaque module.

Bon courage pour la suite de la rédaction.

**Comment by oncletom** [comment]
Bilan des courses :

- j'ai monté Sass
- j'ai monté Postcss
- j'ai descendu Less (et explicité pourquoi l'utiliser face à Sass)

Je préfère passer mon chemin pour Stylus. Je vois davantage de valeur à configurer un PostCSS aux petits oignons.

Merci pour la proposition et les idées annexes 👍
