### ISSUE TITLE
Pré-requis éditoriaux pour l'enregistrement/référencement du livre

### ISSUE THREAD

**Issue by oncletom** [oncletom/nodebook#202]
Pour référencer l'ouvrage sur le réseau de distribution, il faudrait :

- [x] liste des points forts de l'ouvrage
- [ ] en quoi se démarque-t-il des autres ouvrages sur Node.js ?
- [x] biographie à jour histoire de ne pas voir des bêtises sur les fiches Amazon, Fnac and co.

Dépendance sur :

- [ ] nouvelle baseline (Cf. #181)

**Comment by DirtyF** [comment]
> Développeur boulanger itinérant, Thomas cultive autant sa passion pour le développement d'applications web publiques utiles que son levain. Quand il n'est pas dans le pétrin ou en train de jouer avec des données ouvertes, il aime à se ressourcer dans la nature, son appareil photo argentique en bandouillère ou autour d'un verre de vin et d'une bonne assiette de fromages avec sa tribu.

**Comment by oncletom** [comment]
## Points forts

Et différanciants (à mon goût).

* **l'apprentissage de JavaScript**
JavaScript est une pierre angulaire dans l'utilisation de Node.js. Cette mise à niveau permet d'approcher l'environnement de programmation sur des bases saines, que l'on soit débutant·e ou expérimenté·e, que l'on soit designer ou développeur·se.

* **la découverte de l'écosystème**
En apprenant ce qu'il se passe autour de Node, de sa gouvernance et des modules npm, on sait où on met les pieds. On comprend mieux ce qu'on peut faire et où trouver réponse à ses questions.

* **l'approche par l'exemple**
L'apprentissage se fait progressivement en partant d'un cas concret, à partir d'un problème de la vie de tous les jours. On comprend mieux les réflexions et les choix possibles. On peut également approcher l'apprentissage de Node.js par l'angle qui nous correspond le mieux.

**Comment by oncletom** [comment]
J'ai envoyé ça :

> Thomas est un autodidacte qui dévelope des applications web, questionne les usages avec des entretiens utilisateurs et facilite des projets interdisciplinaires. Il est utilisateur de Node depuis la version 0.4 et baigne dans les technologies web depuis 1998.
> 
> À côté de ça, Thomas s'intéresse aux pratiques naturelles d'apprentissage, à la fabrication artisanale du pain, aux approches sensibles et collaboratives, à la photographie argentique et aime passer du temps à randonner dans des espaces calmes et naturels.
> 
> Thomas façonne ses outils de travail au sein de la coopération d'innovation numérique dtc innovation depuis 2017. Avant, il a travaillé pendant 4 années en Angleterre au département Recherche & Développement de la BBC. Il a aussi co-fondé les conférences Sud Web et fait ses armes dans le web à l'agence Clever Age Bordeaux et en travaillant sur des projets open source.
