### ISSUE TITLE
Parler de isomorphic fetch ?

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#203]
> Les navigateurs web et Node n’ont pas accès aux mêmes APIs – Node accède à fs et http tandis que les navigateurs ont File et fetch/XmlHttpRequest ;

https://github.com/oncletom/nodebook/blob/master/chapter-09/index.adoc#51-%C3%89change-ponctuel-de-donn%C3%A9es-avec-fetch

> En résumé, fetch() est idéal pour des demandes ponctuelles de données, du client vers le serveur. Le module npm node-fetch (https://npmjs.com/node-fetch) est une implémentation de fetch() pour Node tandis que whatwg-fetch (https://npmjs.com/whatwg-fetch) s’adresse uniquement à polyfiller les navigateurs web.

Il existe aussi [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) basé sur polyfill Fetch du WhatWG qui propose une API `fetch` commune  pour Node et le navigateur.

**Comment by SebastienElet** [comment]
On voit pas mal d'utilisation de `axios` sur nextjs ou tout ce qui touche au SSR

**Comment by oncletom** [comment]
isomorphic-fetch utilise littéralement les 2 modules cités (node-fetch et whatwg-fetch). Je ne ressens pas trop le besoin d'en rajouter une couche : l'objectif pédagique ici est de comprendre qu'on peut swapper des librairies quand on passe d'un monde à l'autre.

Après le choix de la librairie est libre, que ça soit fetch, axios ou autre.
C'était la première idée qui me passait par la tête de truc dont on voudrait un comportement équivalent front et back.
