### ISSUE TITLE
Utilisation de guillemets doubles --> utilise en fait des guillemets simples

### ISSUE THREAD

**Issue by bertrandgorge** [oncletom/nodebook#226]
Dans le chapitre : 3. Manipuler du texte

// Utilisation de guillemets doubles
console.log('L\'après-midi\nLe soir'); 

Par ailleurs le code ne fonctionne pas.

Enfin, manque le pluriel sur représentent : "Les environnements d’exécution se représente"

**Comment by oncletom** [comment]
Ah ça sent le linting automatique ça :-)

Merci d'avoir signalé ces p'tits bugs, super sympa :-)
