### ISSUE TITLE
Chapitre 4 - Lien interne pour le fonctionnement des modules

### ISSUE THREAD

**Issue by SphinxKnight** [oncletom/nodebook#235]
Dans le chapitre 4, à la ligne 340 (du fichier adoc, je n'arrive pas à construire l'URL pour pointer dessus :(), il y a une référence vers le chapitre 2 pour en savoir plus sur le fonctionnement des modules.

Je n'ai pas encore lu le chapitre 5 mais je pense que c'est plutôt lui qui devrait être visé ? Ai-je mal saisi quelque chose dans le chapitre 2 ? :$ :)

Edit : le chapitre étant identifié comme en cours de rédaction, n'hésitez pas à fermer cette issue sans coup férir si elle est non/im-pertinente :)

**Comment by oncletom** [comment]
Oui c'est le prochain chapitre auquel je vais m'attaquer. C'est un artéfact lié à #184 

Pour construire l'URL, c'est relou en effet de pas pouvoir lier un adoc à la ligne, contrairement à un bon fichier JS des familles :-(
