### ISSUE TITLE
Chapitre 4 - Référence au pattern Singleton au sein du chapitre ou en annexe ?

### ISSUE THREAD

**Issue by SphinxKnight** [oncletom/nodebook#236]
À la ligne 1031, une référence au pattern Singleton est suivie de "explicité plus en détail dans ce même chapitre" : là encore je n'ai pas lu l'annexe sur les Design Pattern mais je pense qu'un pointeur vers cette annexe serait plus pertinent.

Ceci étant écrit, je réalise que je suis impitoyable alors que le contenu est toujours en cours de rédaction pour ce chapitre. **Ne pas hésiter à fermer cette issue si besoin :)**

**Comment by oncletom** [comment]
J'ai tout mis à la poubelle donc il n'y a plus de référence.

_Problem solved_ 😆 

Fais signe si t'as des questions ou que tu vois d'autres incohérences comme ça :-)
