### ISSUE TITLE
Contenu de chapter-03/examples/json/stringify.js incorrect

### ISSUE THREAD

**Issue by lespacedunmatin** [oncletom/nodebook#256]
Le contenu de [chapter-03/examples/json/stringify.js](https://github.com/oncletom/nodebook/blob/master/chapter-03/examples/json/stringify.js) est le même que celui de [chapter-03/examples/json/parse.js](https://github.com/oncletom/nodebook/blob/master/chapter-03/examples/json/parse.js).

**Comment by oncletom** [comment]
Ah. J'ai dû le paumer parce que je me souviens l'avoir écrit :-(

Bon, pas grave. Merci de l'avoir signalé :-)

**Comment by oncletom** [comment]
J'ai poussé un correctif. Tu me diras si ça colle avec ce que tu imaginais.

**Comment by lespacedunmatin** [comment]
Court mais efficace :)
