### ISSUE TITLE
Example de chapitre 3 - ToJSON incomplet

### ISSUE THREAD

**Issue by lespacedunmatin** [oncletom/nodebook#257]
L’exemple de fonctionnement de `ToJSON` au chapitre trois est incomplet, il faudrait ajouter un attribut à l’objet `location` (par exemple `ville`) pour montrer que `ToJSON` ne renvoie que ce qu’on lui demande de retourner, et ignorera les propriétés de l’objet.

**Comment by oncletom** [comment]
OK vu. C'est une bonne idée de préciser que la fonction ne sérialise que ce qui est explicitement défini (et omettra le reste).

J'aurais tendance à le faire dans un exemple complémentaire, avec une transition textuelle indiquant cette subtilité histoire de rester dans le principe "1 exemple = 1 apprentissage".

**Comment by oncletom** [comment]
OK vu. C'est une bonne idée de préciser que la fonction ne sérialise que ce qui est explicitement défini (et omettra le reste).

J'aurais tendance à le faire dans un exemple complémentaire, avec une transition textuelle indiquant cette subtilité histoire de rester dans le principe "1 exemple = 1 apprentissage".

**Comment by oncletom** [comment]
J'ai poussé un changement. Tu me diras si ça correspond à ton idée initiale 🙂

**Comment by lespacedunmatin** [comment]
Oui, c’est parfait :)
