### ISSUE TITLE
Pharse incomplète dans chap3.11.3 − Accesseurs et mutateurs

### ISSUE THREAD

**Issue by lespacedunmatin** [oncletom/nodebook#260]
Au début de la section 11.3 du chapitre 3, on lit : « Ce type particulier de méthode permet […] de gérer comment l’affectation de données. » Il manque un bout de phrase.

**Comment by oncletom** [comment]
Ouais grave ! J'ai poussé une correction.

Je me dis maintenant que cet endroit est un peu pauvre si y'a pas un exemple sur les mutateurs 🙄
