### ISSUE TITLE
Comparaison de nvm avec rbenv

### ISSUE THREAD

**Issue by clairezed** [oncletom/nodebook#282]
**Dans le chapitre 2**, partie 1.2, tu expliques : 

> Si vous venez d’un autre univers de programmation, nvm est l’équivalent de rbenv dans le monde Ruby, de phpenv dans le monde PHP ou encore de virtualenv pour Python.

Je ne connais pas suffisamment le fonctionnement de nvm pour juger, mais je me demande si des rubyistes pinailleront pas -> nvm est-il l'équivalent de **rbenv** ou **rvm** ?

[Cet article](https://www.mindfiresolutions.com/blog/2018/01/rbenv-vs-rvm/) qui explique le fonctionnement des deux te permettra peut-être de trancher ?

**Comment by clairezed** [comment]
Fondamentalement, c'est quand même pas très important, hein.

**Comment by oncletom** [comment]
Merci @clairezed 🙂 

Tu utilises rvm ou rbenv ? Tu penses que des Rubyistes qui passeraient à Node connaitraient rvm mais pas rbenv ?

**Comment by clairezed** [comment]
Moi j'utilise rvm, mais généralement les rubyistes connaissent (ont entendu parler) des 2. Vu qu'il n'y a pas forcément un enjeu fort, je pense que tu peux facilement t'en tirer avec une pirouette genre *" l’équivalent de rvm ou rbenv dans le monde Ruby"*.
