### ISSUE TITLE
Typo chapitre 2 - branche ou version

### ISSUE THREAD

**Issue by clairezed** [oncletom/nodebook#283]
**Dans le chapitre 2, partie 1.2**
**J'ai lu**…

>  De même, taper nvm use default ou nvm use v8 nous fera basculer vers **la branche la version v8.11.1**.

**Suggestion de correction** :
C'est peut-être plutôt ça que tu voulais dire ? ->

> De même, taper nvm use default ou nvm use v8 nous fera basculer vers la version v8.11.1.

**Comment by oncletom** [comment]
Oui en effet c'est incomplet, merci de l'avoir repéré 🙂 
Je me demande s'il ne manque pas des mots entre _branche_ et _la version_.

Aujourd'hui ça me donnerait envie d'écrire _la version la plus récente de la branche v8, par exemple _v8.11.1_.

Je regarderai à nouveau en contexte pour voir 🙂
