### ISSUE TITLE
Parler de https://npm-stat.com/

### ISSUE THREAD

**Issue by NerOcrO** [oncletom/nodebook#297]
Je viens de découvrir ce site et du coup, j'ai comparé express à hapi (dont on m'a dit le plus grand bien) et j'avoue que la dernière stat qui porte sur l'année en dit long sur l'adoption de ce module :

hapi : https://screenshots.firefox.com/vaJ6oDtvrrYDS3cs/npm-stat.com
express : https://screenshots.firefox.com/DKJjQKcXca17tcHr/npm-stat.com

Après, ça n'empêche pas, évidemment, de regarder en détail ce que fait l'un et l'autre par rapport à son projet.

**Comment by oncletom** [comment]
Quand tu mets côte à côte npmjs.com/express et npmjs.com/hapi, ça te fait le même effet qu'avec npm-stat.com ?

J'ai tendance à me méfier des outils "magiques" qui font beaucoup de choses pour nous — je leur préfère des outils "explicites".

**Comment by NerOcrO** [comment]
Pour dire vrai, quand je les compares sur npmjs.com, je ne me dis rien...
À la limite, je me fis juste au "weekly downloads" pour me donner une tendance.

Je suis d'accord avec toi, il n'y a pas d'outils magique et c'est pour ça que je remplie ma trousse à outils de pleins d'outils comme celui là pour me décider à prendre tel ou tel module. C'est juste à titre indicatif.
