### ISSUE TITLE
Support des modules JavaScript dans les navigateurs Web

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#308]
Les principaux navigateurs supportent maintenant en natif l'import de modules. Quel impact sur l'écriture d'applications front-end?

- L'article d'Addy Osmani et Mathias Bynen :  https://developers.google.com/web/fundamentals/primers/modules
- Une explication détaillée du fonctionnement des modules ES: 
https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/

**Comment by oncletom** [comment]
J'en parle un peu dans cette section https://oncletom.io/node.js/chapter-09/#modules-es2015

Tu penses qu'elle est à actualiser ?

J'ai pas trop envie de pousser le truc tant qu'il y a les `.mjs` — j'ai le sentiment que Node va finir par accepter les modules ESM sans cette extension. Je vois pas encore beaucoup modules qui proposent du module ESM sur npm, c'est encore prématuré pour en faire une généralité qui permet de se passer d'outillage — l'import de module npm dans le browser c'est 🤨

**Comment by oncletom** [comment]
À préciser si jamais ça ne répondait pas à ton intention initiale 🙂
