### ISSUE TITLE
Erreur au lancement de bin/cli.js

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#314]
En lisant le chapitre 08

**J'ai lancé**  `node bin/cli.js` dans mon repo local de nodebook après avoir lancé `git pull`

**Et il s'est affiché ça**…

```sh
node bin/cli.js
(node:57215) UnhandledPromiseRejectionWarning: TypeError: yargs.locale(...).scriptName is not a function
    at updateNotifier.then.then (/Users/frank/code/nodebook/bin/cli.js:19:8)
    at <anonymous>
(node:57215) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57215) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**C'était dans le** terminal 

**Sous** macOSX 10.13.6

**Avec Node version** v10.5.0/v10.0.0/v8.11.1

**Comment by oncletom** [comment]
@DirtyF est-ce que tu as fait `npm install` suite au `git pull` ?

**Comment by DirtyF** [comment]
ah non j'avais zappé, désolé.

**Comment by oncletom** [comment]
@DirtyF pas de problème, content que c'était que ça 🙂 j'aurais aussi pu zapper de commiter un fichier ou deux.

J'ai ajouté depuis peu un test basique de la ligne de commande pour m'assurer que le CLI cassait pas entre 2 publications (parce que ça a été le cas et ça passait inaperçu).

https://github.com/oncletom/nodebook/blob/60401e23ac2ffd9269f7f76e0ea234b3e293da26/.travis.yml#L22-L24
