### ISSUE TITLE
Ajouter les contenus des fichiers javascript utilisés dans les exemples

### ISSUE THREAD

**Issue by loicm** [oncletom/nodebook#33]
Chapitre 2 > Node, JavaScript et ECMAScript > Variables globales dans Node.js > process

Il pourrait être bien de montrer le contenu des fichiers *process.js*, *uppercase.js* et *interrupt.js* pour faciliter la compréhension des exemples par le plus grand nombre.

**Comment by oncletom** [comment]
@loicm oui bonne idée :-) tu peux les inclure via un `include::` (prends exemple sur d'autres bouts de code). À partir du moment où le chemin renseigné est valide, le contenu du fichier sera intégré au HTML/livre papier.
