### ISSUE TITLE
Attribut <mark> affiché dans les substitutions de source JSON

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#365]
En parcourant [la version web du chapitre 5](https://oncletom.io/node.js/chapter-05/#install.version
), je m'aperçois que les emphases fortes dans les snippets de code JSON sont rendues avec une balise HTML `<mark>` qui n'est pas interprétée, mais affichée telle quelle. 

Exemple :

```json
{
  ...
  "dependencies": {
    "cowsay": "^1.3.1",
    "lodash": "<mark>^2.4.2</mark>"
  }
}
```

**Comment by oncletom** [comment]
Très bien vu !

En cherchant rapidement, le problème est lié à https://github.com/oncletom/asciidoctor-prism-extension, qui met en forme les blocs d'exemple. Sans cette extension activée, le résultat est celui attendu (du texte surligné en jaune).

**Comment by oncletom** [comment]
C'est OK depuis #371 👌 

<img width="382" alt="image" src="https://user-images.githubusercontent.com/138627/56341356-17560900-61b5-11e9-99ab-6132f3b27a97.png">
