### ISSUE TITLE
Des "&amp;" à la place des "&" dans l'exemple "instructions/if.js" du chapitre 3 (via navigateur)

### ISSUE THREAD

**Issue by Carl20cent** [oncletom/nodebook#372]
**Dans le chapitre** 3
**J'ai lancé l'exemple suivant** : chapter-03/examples/instructions/if.js

**Et il s'est affiché ça** : des `&amp;` à la place des `&`. Ce qui fait que l'exemple "instructions/if.js" ne peut pas se lancer directement dans le navigateur via RunKit.
(Ce souci doit surement se retrouver ailleurs)

![Capture d’écran 2019-03-27 à 10 49 49](https://user-images.githubusercontent.com/27127044/55066468-25b17900-507e-11e9-974a-da2b6201cb04.jpg)

**C'était dans le** navigateur Chrome

**Sous** Mac OS

**Comment by oncletom** [comment]
Merci :-)

**Comment by oncletom** [comment]
#371 résout ce problème (sans faire exprès).
