### ISSUE TITLE
Certains des liens qui mènent à un autre chapitre ne fonctionnent pas

### ISSUE THREAD

**Issue by Carl20cent** [oncletom/nodebook#373]
**Dans le chapitre :** 3 (mais potentiellement aussi dans les autres chapitres)

**Le contexte :** Lecture du livre dans Chrome (Mac OS)

**Le souci rencontré :** Certains des liens qui mènent à autre chapitre ne fonctionnent pas. 
Comme par exemple le lien **chapitre suivant** tout à la fin du chapitre 3 (https://oncletom.io/node.js/chapter-03/#conclusion)

![Capture d’écran 2019-03-27 à 11 24 00 - ZOOM](https://user-images.githubusercontent.com/27127044/55068936-39aba980-5083-11e9-8cf7-8b3d80c0da5a.jpg)

Par contre, il semblerait que dans le chapitre 2, on trouve des liens qui mènent vers d'autres chapitres et qui fonctionnent bien !
(comme le lien "Déploiement d’une image Docker" présent dans le chapitre 2 et qui mène bien au chapitre 6 : http://oncletom.github.io/nodebook/chapter-02/#install-docker )

**Suggestion de correction** :
En regardant un peu comment est fait le "code source" du chapitre, il semblerait qu'un lien vers un autre chapitre qui finit par un "#" fonctionne bien. Mais est-ce qu'un simple "#" peut résoudre le problème, à toi de me le dire 😉 

Encore merci et bonne continuation !
/Carl

**Comment by oncletom** [comment]
Bien vu et merci :-)

Dans le code source, le passage correspond est `<<../chapter-04/index.adoc,chapitre suivant>>`.

C'est subtil, je n'ai pas compris pourquoi encore, parce qu'en ajoutant un dièse au nom du fichier, ça explicite l'ancre (aucune) et le lien inter-document se fait : `<<../chapter-04/index.adoc#,chapitre suivant>>`.

**Comment by oncletom** [comment]
Merci @Carl20cent ! Il y avait 11 coquilles en tout 🙂 (cf. d17bf05c11aaf7d86baebe555aed0b4233e4f6f7).
