### ISSUE TITLE
chapter-02 / 4.3. Versions majeures > phrase à revoir

### ISSUE THREAD

**Issue by gurvanhenry** [oncletom/nodebook#384]
**Dans le chapitre 02**
4.3. Versions majeures

**J'ai lu**…

> Sur notre ordinateur de développement : nous **prenins** du temps pour tester nos applications et nous assurer de leur bon fonctionnement.

**Suggestion de correction** :

> Sur notre ordinateur de développement : nous **(prendrions | prenions)** du temps pour tester nos applications et nous assurer de leur bon fonctionnement.

... ou autre correction, à toi de voir

**Comment by oncletom** [comment]
Je crois que je le pensais au présent, `… nous **prenons** du temps pour …`.

Merci :-)
