### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Menaquinone** [oncletom/nodebook#452]
Hello,

Tout d'abord, merci pour ton livre : cela fait quelques temps que je souhaite me mettre sur Node et ton livre m'a aidé à sauter le pas !

Pour l'issue :

Je n'arrive pas à lire le livre en local, sur mon localhost:3000 je n'ai qu'une page avec marqué `Cannot GET /`

Je suis passé par NVM pour utiliser node v10, aucun soucis lors de l'installation des chapitres.
J'utilise ta commande `nodebook read` pour démarrer le serveur.

Merci d'avance,

**Comment by thom4parisot** [comment]
Salut !

Très content que cette lecture t'aide à sauter le pas :-) Qu'est-ce qui te retenait de le faire jusqu'à présent ?

Je te confirme que reproduis le problème, merci de l'avoir signalé !
Je regarde et corrige ça sous peu.

**Comment by thom4parisot** [comment]
Corrigé dans la version `v1.0.13` !

**Comment by Menaquinone** [comment]
Une explication clair et en profondeur.
Et je devrais (enfin) pouvoir mettre en pratique au boulot alors cela aide pas mal.

**Comment by thom4parisot** [comment]
Super, merci :-)

Fais signe si tu trouves autre chose qui cloche ou si tu ressens le besoin que je clarifie un exemple ou passage du livre.

**Comment by Menaquinone** [comment]
Pour le moment j'en suis à la première lecture mais je n'hésiterais pas à revenir vers toi si je trouve quelque chose.
