### ISSUE TITLE
Bonnes pratiques pour des applications robustes

### ISSUE THREAD

**Issue by oncletom** [oncletom/nodebook#48]
- Gestion des erreurs
- Erreurs courantes
- Environnements de configuration
- Sécurité
- Logging
- Débogage
  1. Prévenir les plantages
     1. Erreurs et exceptions
     2. Le problème des exceptions
     3. De l'utilisation des `domains`
     4. Écouter les évènements système
  2. Cas typiques de code à surveiller
     1. Erreurs de syntaxe
     2. Typage inattendu
     3. Valeurs nulles
     4. Upload de fichiers
     5. Évènements via `.on('error')`
     6. Callbacks
     7. Épuisement de mémoire
     8. _Race condition_
  3. Sécurité des données
     1. Données malicieuses
     2. Infiltration du système de fichier
     3. Échapper les données consommées par les utilisateurs
     4. RegExp
     5. CSRF
     6. XSS
     7. Attaques par injection
  4. Déboguer son code
     1. Node.js en mode debug avec `node --debug`
     2. Module `node-debug`
     3. Webstorm IDE
  5. Tester son code
     1. Configurer son `package.json`
     2. Écrire les tests
     3. Exécuter les tests
     4. Utilisation des espions, bouchons etc. avec _Sinon.js_
     5. Connaître sa couverture de code avec _blanket_
  6. Intégration et déploiement continu
  7. Principes
  8. _Travis CI_
  9. _Coveralls_
  10. _Jenkins_
  11. _Strider_
  12. _Codeship_
- Node.js avancé
  1. De la bonne utilisation de `package.json`
  2. `npm`
     1. Dépendances optionnelles (`optionalDependencies`)
     2. Dépendances de pairs (`peerDependencies`)
     3. Variables d'environnement
     4. `npm run-script`
     5. Geler les versions avec `npm shrinkwrap`
     6. Développer son module Node.js avec `npm link`
  3. Node.js sans JavaScript
     1. ECMAScript 6 avec traceur
     2. TypeScript
  4. `npm` sans Node.js
     1. Composants Web
     2. Mozilla Jetpack
     3. `libc`
     4. Titanium
  5. `node-gyp` ou écrire en C++ pour `libuv`
  6. Flags avancés (`node --v8-options`)

**Comment by borisschapira** [comment]
Monitoring et reprise sur incident en cas d'interruption du process node ?
