### ISSUE TITLE
Mots manquants dans le chapitre 3

### ISSUE THREAD

**Issue by oliverpool** [oncletom/nodebook#49]
Dans le chapitre 3:

> Au lieu d’exécuter trois la fonction `messageAbbr`, nous voulons au contraire exécuter trois traitements différents sur le résultat.

Je pense que ça devrait être (au moins pour le sens):

> Au lieu d’exécuter successivement les trois fonctions `uppercaseAsync`, `splitWordsAsync` et `abbreviateAsync` sur le résultat de la fonction précédente, nous voulons au contraire exécuter trois traitements différents sur le résultat.

---

Dans tous les cas, un grand merci pour ce livre très intéressant et bien écrit! (j'ai enfin vraiment compris ce qu'était Node grace à la phrase "Node est une API JavaScript pour manipuler des ressources système.")

**Comment by oncletom** [comment]
Oui ce passage est vraiment confus. Je t'avoue qu'en me relisant je ne comprends pas ce que je voulais signifier :-D Ni même le sens de l'exemple !

Ta suggestion est très certainement correcte mais faudrait que je me repenche sur l'exemple pour mieux en cerner sa portée.

Content que le contenu te plaise et si t'as quelconque idée d'amélioration, de choses que tu aimerais savoir, ou de clarification, t'es le bienvenu :-)

**Comment by Scriptura** [comment]
Toujours au chapitre 3 :
> C’est l’outil que vous devrez utiliser pour démarrer vos applications sur par la plateforme Heroku après déploiement.
