### ISSUE TITLE
Chapitre 3 : double appel à `uppercaseAsync` ?

### ISSUE THREAD

**Issue by oliverpool** [oncletom/nodebook#50]
Dans [message-abbr-promisified.js](https://github.com/oncletom/nodebook/blob/master/chapter-03/examples/src/snippets/message-abbr-promisified.js#L37-L38), il me semble que la fonction `uppercaseAsync` est appelé 2 fois (alors qu'une fois devrais suffire):

```js
module.exports = function messageAbbr(message){
  return new Promise(function(resolve, reject){
    return uppercaseAsync(message)
      .then(uppercaseAsync)
      .then(splitWordsAsync)
      .then(abbreviateAsync)
      .then(resolve)
      .catch(reject);
  });
};
```

**Comment by oncletom** [comment]
Toutafé, bonne remarque ! :-)

Si tu changes le code et soumets une PR, je l'accepterai aussitôt :-)

Merci et bien vu !
