### ISSUE TITLE
Chapitre 1, SemVer

### ISSUE THREAD

**Issue by Scriptura** [oncletom/nodebook#53]
Dans la brève description de SemVer j'ajouterais que le numéro d'une version majeure égale à 0 est considérée comme étant en dev, non stable, et par conséquent ne suit pas la règle de versionning précitée (`MAJEUR.MINEUR.CORRECTIF`).

Cf. http://semver.org/lang/fr/#spec-item-4

**Comment by oncletom** [comment]
Bonne remarque 👍
