### ISSUE TITLE
Mentionner node --inspect

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#65]
Le debug est rapidement évoqué dans le chapitre 2, je ne sais pas s'il y aura une partie dédiée à ça, mais le nouveau mode inspect semble suffisamment utile pour être mentionner

https://nodejs.org/dist/latest-v7.x/docs/api/debugger.html#debugger_v8_inspector_integration_for_node_js

Un exemple d'utilisation avec les Chrome DevTools : 

![node inspect dans devtools](https://umaar.com/assets/images/dev-tips/improved-node-debugging.gif)

**Comment by oncletom** [comment]
Y'a un truc de prévu que j'ai mis dans #34 et qui a priori devraient être développés dans le chapitre 7. Y'a [devtool](https://github.com/Jam3/devtool) pour les versions antérieures et quelques autres pistes développées dans https://github.com/nodejs/node/issues/2546 pour les versions de node antérieures à la version 7.

Je devrais ajouter mention dans le chapitre 2, pointant vers la section adéquate du chapitre 7.

Excellente suggestion 👍

**Comment by oncletom** [comment]
Fait dans 40e6a7e14ca40cea874f4849f5e3bea2c4ed7192 et complété avec #186
