### ISSUE TITLE
Sélection de modules pour Atom

### ISSUE THREAD

**Issue by oncletom** [oncletom/nodebook#68]
En plus de …

- https://atom.io/packages/atom-ternjs

… j'ai spotté, pour l'Annexe A :

- https://atom.io/packages/autocomplete-modules
- https://atom.io/packages/linter-eslint
- https://atom.io/packages/pigments
- https://atom.io/packages/docblockr
- https://atom.io/packages/editorconfig
- https://atom.io/packages/file-icons
- https://atom.io/packages/language-babel
- https://atom.io/packages/linter-sass-lint
- https://atom.io/packages/tablr

**Comment by DirtyF** [comment]
Y'en a pléthore, pour rester uniquement sur JS, quelques autres : 

* https://atom.io/packages/es6-javascript
* https://atom.io/packages/linter-js-standard
* https://atom.io/packages/atom-formatter-jsbeautify
* https://atom.io/packages/lebab :)
