### ISSUE TITLE
Chemin du fichier data/books.csv

### ISSUE THREAD

**Issue by DirtyF** [oncletom/nodebook#69]
```shell
$ node chapter-02/examples/src/print-csv.js
/Users/frank/github/nodebook/chapter-02/examples/src/print-csv.js:13
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/frank/code/nodebook/chapter-02/examples/src/data/books.csv'
```

Afin de permettre l'exécution du script `print-csv.js`, le dossier `data ` devrait se trouver dans le répertoire `src`, or il est dans le répertoire parent.

- soit on met le code du script à jour en construisant le chemin en ajoutant `..` pour qu'il fonctionne,
- soit on déplace le dossier `data` et cela demande aussi de modifier le code asciidoc.

**Comment by oncletom** [comment]
Œil de lynx ;-) Merci !
