### ISSUE TITLE
Polyfills

### ISSUE THREAD

**Issue by oncletom** [oncletom/nodebook#71]
- [ ] [polyfill.io](https://polyfill.io)
- [ ] [babel-polyfill](https://babeljs.io/docs/usage/polyfill/)
- [ ] [babel-preset-env](https://npmjs.com/babel-preset-env)

**Comment by ThomasG77** [comment]
Pour ajouter de l'eau au moulin si tu n'es pas déjà tombé dessus https://w3ctag.github.io/polyfills/
En plus, ce n'est pas long à lire

**Comment by oncletom** [comment]
Salut @ThomasG77, c'est une très bonne idée !
Je l'ai justement référencé en écrivant dans le train toute à l'heure :-)

<img width="1015" alt="screen shot 2017-02-13 at 16 53 13" src="https://cloud.githubusercontent.com/assets/138627/22890543/f46ceb1c-f20c-11e6-9b04-cef7aff21e27.png">
