### ISSUE TITLE
Workflow build time + dev time

### ISSUE THREAD

**Issue by oncletom** [oncletom/nodebook#72]
# Build Time

- [x] browserify
- [x] babel

# Dev Time

- [x] watchify
- [x] browser-sync
- [ ] HMR

**Comment by DirtyF** [comment]
What about webpack?

**Comment by oncletom** [comment]
Webpack c'est cool mais c'est moins modulaire et trop compliqué à expliquer en terme de config.

browserify a l'avantage d'être progressif en terme de configuration. L'ajout de transform se fait progressivement sans exigence sur ta codebase.

**Comment by oncletom** [comment]
Une partie a été adressée par 7eed565ba41b4af2e676a813863cdc787f87d3c5, 5c51a348ab3adb6e70542229d48c9643bd785695 et 810490ffc02ac94ad13e6bbb4e194998f2f7cb6c

**Comment by oncletom** [comment]
Watchify avec 6d1e21c.
