### ISSUE TITLE
yarn

### ISSUE THREAD

**Issue by oncletom** [oncletom/nodebook#96]
Intéressant à plus d'un titre.

Faut que je vois encore dans quel chapitre j'en parle.

Merci @gmarty pour la suggestion !
> https://twitter.com/g_marty/status/824631676299010049

**Comment by DirtyF** [comment]
ça aurait du sens  d'ajouter une note sur Yarn dès le chapitre 3 dans la partie cycle de vie du projet.

**Comment by oncletom** [comment]
Hop dans 56e093b.

@DirtyF fais signe si ça te laisse sur ta faim/tu penses que ça répond pas trop à la question.

**Comment by NerOcrO** [comment]
Sujet intéressant mais qui me laisse perplexe sur l'utilité de mettre en place Yarn sur mes projets :
https://mixmax.com/blog/to-yarn-and-back-again-npm

**Comment by DirtyF** [comment]
👍 @oncletom entre temps `npm` a bien rattrapé son retard, surtout en ce qui concerne la rapidité d'install des paquets, du coup `yarn` présente bien moins d'intérêt qu'à sa sortie où la différence était vraiment significative.
